name: Postman collection run

on:
  push:
    branches:
      - main

jobs:
  newman_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install newman & HTML extra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run Tests on Dev or Stage
        run: |
          newman run HW_Part_3_Noskova_Alina.postman_collection.json -r cli,htmlextra,junit

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Rename report
        if: always()
        run: |
          ls
          pwd
          cd newman
          mv *.html index.html
      
      - name: Host Report on GH pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: newman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy report to Github Pages newman directory
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: newman
